config/routes.rb
Railsajax::Application.routes.draw do
  get "pages/index"
  get "pages/detalhe"
  get "pages/login_or_subscribe"
  post "pages/signin"

  resources :products
  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :price
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def detalhe
  end

  def signin
  	logger.info "------->>>>>> Logado com Sucesso!"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsajax" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Railsajax</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/_detalhe.html.erb
<h1>Pages#detalhe</h1>
<p>Find me in app/views/pages/detalhe.html.erb</p>
<%= link_to "Voltar", pages_index_url, remote: true, class: "btn btn-warning"%>

app/views/pages/_index.html.erb
<div id="index">
<h1>Pages#index</h1>
<%= link_to "Detalhe", pages_detalhe_url, remote: true, class: "btn btn-warning"%>
<%= link_to "Login/Subscribe", pages_login_or_subscribe_url, remote: true, class: "btn btn-warning"%>
</div>
<div id="pages"></div>
<div id="login-or-subscribe-modal" class="modal hide fade"></div>

app/views/pages/_login_or_subscribe.html.erb
<div class="modal-header">
	<h3>Login/Subscribe</h3>
</div>
 <div class="modal-body">
 	<%= simple_form_for :signin, :url => pages_signin_url, remote: true  do |f| %>
	  <%= f.input :email %>
	  <%= f.input :password %>

 </div>

	 <div class="modal-footer">
		<%= f.submit "Save", class: "btn" %>
	 	<%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
	 </div>
 	<%end%>

app/views/pages/_signin.js.erb
// $("#index").empty();
// $("#login-or-subscribe-modal").modal("hide")
// $("#index").html("<%= escape_javascript(render 'index') %>");
// $("#index").show();
alert("oi");

app/views/pages/detalhe.js.erb
$("#index").empty();
$("#pages").empty();
$("#index").hide();
$("#pages").html("<%= escape_javascript(render 'detalhe') %>");
$("#pages").show();

app/views/pages/index.html.erb
<%= render 'index'%>

app/views/pages/index.js.erb
$("#index").empty();
$("#pages").empty();
$("#pages").hide();
$("#index").html("<%= escape_javascript(render 'index') %>");
$("#index").show();

app/views/pages/login_or_subscribe.js.erb
$("#index").show();
$("#login-or-subscribe-modal").html("<%= escape_javascript(render 'login_or_subscribe') %>");
$("#login-or-subscribe-modal").modal("show")

app/views/products/_delete.html.erb
<div class="modal-header">
  <h3>Delete Product</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @product.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This Product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/products/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@product.name}" %></h3>
</div>
<%= render "form" %>

app/views/products/_form.html.erb
<%= form_for @product, remote: true do |f| %>
 <div class="modal-body">
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
  </div>
  <div class="modal-footer">
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
    </div>
  </div>
<% end %>

app/views/products/_new.html.erb
<div class="modal-header">
<h3>New Product</h3>
</div>
<%= render "form" %>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/products/create.js.erb
<%= render "save" %>

app/views/products/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/products/destroy.js.erb
<%= render "save" %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Product", new_product_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-product"></div>

  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>

    <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.price %></td>
      <td>
        <%= link_to 'Show', product, :class=> "btn" %>
        <%= link_to 'Edit', edit_product_path(product), remote: true,  :class=> "btn" %>
        <%= link_to 'Destroy', product, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<div id="product-modal" class="modal hide fade"></div>

app/views/products/new.js.erb
alert("oi");
// $("#product-modal").html("<%= escape_javascript(render 'new') %>")
//$("#product-modal").modal("show")

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/update.js.erb
<%= render "save" %>